### ISSUE TITLE
Mod suggestion - Skyrim Unlocked

### ISSUE THREAD

**Issue by pamposzek** [giraldiego/NOIR#1]
https://github.com/Kaenguru-Knobel-Kette/skyrim-unlocked - this mod allows to access areas locked by quests and allows to pick locks for some doors requiring keys. For example, you can get broken Azura's Star without the need to go to the shrine first. IMO it's pretty immersive and nice, there are no more magical mines that uncollapse themselves or magical parts dungeons which just appear out of nowhere the second you talk to a guy.

This doesn't break any quests, unless you explicitly enable specific dungeons in MCM and get a warning box (e.g. unlocking Saarthal will break Mage Guild questline). That's pretty nice if you want to get Gauldur's Amulet for example, without having to do the magic initiation, or get access to areas if you're sure you won't do X questline on your character. It includes patch for ESF - companions, aside from that it shouldn't be conflicting much. Another eqample, maybe not super immersive, but you can unlock Labyrinthian in MCM without doing the questline, if you want to test your high level character without the hassle or having to become a mage.

**Comment by giraldiego** [comment]
Thank you, I am checking it, it seems the SSE version is going to be improved by the author, has you used the SSE version from github without problems in Requiem?

**Comment by pamposzek** [comment]
Seems like the author is inactive, but I've been using his SE version since I can remember, without issues. Unlocking Saarthal or Labyrinthian works as intended, and other quests which affect the same cells also work. As author says on his LE page about this future improvement: "This doesn't mean that the current version has actual issues that negatively affect the game in any way.", which is exactly my experience with this mod.

From what I see, if you load ELE after this, the only compatibility issue are 2 NPCs - I'm pretty sure Requiem Patch Central has the patch for NPCs (well, if one is using 3tweaks or NPC Statefix, manual patch is needed, but it's super simple, literally drag few things from Skyrim Unlocked) and other two, so ESF - Companions (1 quest record) and LAL have patch included in the download.

**Comment by giraldiego** [comment]
Implemented in 1.3.1
