### ISSUE TITLE
Even More Crafting Stations - floating chest near Winterhold

### ISSUE THREAD

**Issue by MoonShadowFan** [giraldiego/NOIR#10]
Forge Outside Winterhold added by Even More crafting stations has floating chest next to it.

RefID = 0C00193A

![enb2020_4_9_05_09_28](https://user-images.githubusercontent.com/63240913/78857934-ca50ef80-7a22-11ea-8b15-2aae073cb0fc.jpg)

New Game - coc Winterhold - go outside Winterhold to crafting station sitting in middle of nowhere.

NOIR 1.3 latest from 7th April

**Comment by giraldiego** [comment]
thank you for this, but it is Crafting Location Improved, I will fix it though

**Comment by giraldiego** [comment]
Solved in 1.3.3
