### ISSUE TITLE
Change to the subtle version of racial body morphs and Furniture Height Size Fix

### ISSUE THREAD

**Issue by MoonShadowFan** [giraldiego/NOIR#11]
With the "full" version of racial body morphs the Nords particularly rest their hands way above the bar or whatever they are leaning on. You might want to consider using the subtle version. I changed it and it's much less noticible in the inns and shops. Also the suggestion of using "Furnitures Height Size Fix enhanced 1.01" seems to have worked for the wagon drivers - but that might just have been my issue.

I added the subtle version and then copied the heights into IA's Chasing the dragon patch and removed the subtle esp. Seems to be working ok, I guess you could add the changes to one of your other patches if you think it's worth it.

**Comment by giraldiego** [comment]
Thank you, I will check on this, I was thinking in even remove Racial Body Morphs entirely, but I like how npc look.

**Comment by MoonShadowFan** [comment]
It's a difficult one - in OLDRIM it worked because the NPC's were scaled when leaning on anything so just shrunk to fit. But that does not seem to happen with your build - not sure if that's SE or something else. Unless you have something in the build that stops NPC scaling?

**Comment by giraldiego** [comment]
The author changed things in the SE version of RBM, anyway, I implemented your suggestion in 1.3.3, open a new issue if you happen to find a better solution. 
Regards
