### ISSUE TITLE
The water in Riften's canal has disappeared

### ISSUE THREAD

**Issue by Mummelpuffin** [giraldiego/NOIR#14]
[Check this out.](https://postimg.cc/gallery/K3N84kz)

[One more just for clarity](https://postimg.cc/gXKv18RN/34ff1067)

I know, weird, right?

Modlist version 1.3.5

All I've added to the list is SkyHUD and the ENB particle patch.
I've enabled Realistic AI Detection but that really shouldn't matter.
Not sure what the NSUTR and OCW patches are so I left them disabled (which they were when I started).
I've applied the 1.3.5 hotfix, Cathedral - Water.esp is enabled.

[Someone in this thread](https://www.reddit.com/r/ultimateskyrim/comments/9ncv8d/missing_water_in_riften/) claims that this has something to do with a mod moving something in Riften's worldspace, but it doesn't appear as though that's happened.

The weirdest thing, which honestly kind of invalidates this, is that I swear Riften was fine when I first showed up. Somewhere along the line, swapping between ENBs and messing with the grass section of the .ini files, I walked outside and this happened.

EDIT: I did a reinstall of the modlist (left my downloads folder and base Skyrim installation intact, deleted the modlist installaton and saves n' things, even deleted / redownloaded Skyrim.esm / Update.esm on a wild hunch) and this issue is still present. It should probably be noted that the one time I *think* I remember the water being there is when I first entered the city by the north gate. Re-loading the game after the fact, or starting in the Bee & Barb, has always caused this problem. I might start someone outside Riften and enter through the north gate again to see what happens.

**Comment by Mummelpuffin** [comment]
Solved by Codygits on Discord, it's a pretty simple fix
![riften_water_fixed](https://user-images.githubusercontent.com/20485701/80921131-7051fa00-8d42-11ea-9818-2bafeabe432c.png)

**Comment by giraldiego** [comment]
Thank, fixed in the latest release.
