### ISSUE TITLE
Mod with dot cursor

### ISSUE THREAD

**Issue by Fjodik** [giraldiego/NOIR#3]
**Any mod with dot crosshair**

As I really love playing ranged character I would like to see some replacement for the default crosshair which is in my opinion really ugly.

**DOT CROSSHAIR**
https://www.nexusmods.com/skyrimspecialedition/mods/8891

**SKY HUD**
https://www.nexusmods.com/skyrimspecialedition/mods/463

**Comment by pamposzek** [comment]
I don't personally use Sky HUD, but Dot Crosshair is awesome and I always use this. Small and simple mod.

**Comment by giraldiego** [comment]
> 
> 
> **Any mod with dot crosshair**
> 
> As I really love playing ranged character I would like to see some replacement for the default crosshair which is in my opinion really ugly.
> 
> **DOT CROSSHAIR**
> https://www.nexusmods.com/skyrimspecialedition/mods/8891
> 
> **SKY HUD**
> https://www.nexusmods.com/skyrimspecialedition/mods/463

I agree with you, the ch is bad, and when sneaking is even worst, I will take a look

**Comment by giraldiego** [comment]
Implemented DOT CROSSHAIR
