### ISSUE TITLE
Wolfs yield a horse meat

### ISSUE THREAD

**Issue by Fjodik** [giraldiego/NOIR#6]
**Describe the bug**
All wolfs I have killed had besides the proper loot also a horse meet as loot.

**To Reproduce**
Kill any wolf and check its loot.

**Modlist version** 
1.3

**Did you add any additional mods?** 
No

**Comment by Blackiiee** [comment]
Yeah I'm playing on 1.3 aswell, and I can confirm this.

**Comment by giraldiego** [comment]
Solved in latest release!.
